name: "scp"
version: "0.1.0"
usage: "helm scp"
description: "Package and upload Helm charts over SCP"
ignoreFlags: false
platformCommand:
  - os: linux
    arch: amd64
    command: "$HELM_PLUGIN_DIR/bin/helmscp-linux"
  - os: windows
    arch: amd64
    command: "$HELM_PLUGIN_DIR/bin/helmscp-windows"
  - os: darwin
    arch: amd64
    command: "$HELM_PLUGIN_DIR/bin/helmscp-darwin"
downloaders:
- command: "bin/helmscp"
  protocols:
    - scp
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"